### ISSUE TITLE
Feature coverage?

### ISSUE THREAD

**Issue by saurabhnanda** [pbrisbin/liquid#1]
How many features of the Liquid templating language are supported by this package? I have a Liquid template which is being parsed perfectly in Ruby, but is throwing errors when parsed with this package.

For example, is `assign` supported?

**Comment by pbrisbin** [comment]
I'm sorry @saurabhnanda this was a weekend hack, didn't get very far, and is now effectively dead. I will update the README to make this clear. I apologize if you were looking for a fully-formed liquid-templating package for Haskell, maybe https://github.com/projectorhq/haskell-liquid is more active?
